In [ ]:
import pandas as pd

import numpy as np

In [ ]:
dados_1semestre = 'Preços semestrais - AUTOMOTIVOS_2025.01.csv'
df_1semestre = pd.read_csv(dados_1semestre, sep=';', low_memory=False)
df_1semestre.head(3)

C:\Users\thales.nogueira\AppData\Local\Temp\ipykernel_45204\666181149.py:2: DtypeWarning: Columns (0: Regiao - Sigla, 1: Estado - Sigla, 2: Municipio, 3: Revenda, 4: CNPJ da Revenda, 5: Nome da Rua, 6: Numero Rua, 7: Complemento, 8: Bairro, 9: Cep, 10: Produto, 11: Data da Coleta, 12: Valor de Venda, 13: Unidade de Medida, 14: Bandeira) have mixed types. Specify dtype option on import or set low_memory=False.
  df_1semestre = pd.read_csv(dados_1semestre, sep=';')

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,CE,SOBRAL,ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,GASOLINA,01/01/2025,"6,29",NaN,R$ / litro,RAIZEN
1,NE,CE,SOBRAL,ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,GASOLINA ADITIVADA,01/01/2025,"6,49",NaN,R$ / litro,RAIZEN
2,NE,CE,SOBRAL,ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,DIESEL S10,01/01/2025,"6,19",NaN,R$ / litro,RAIZEN

In [ ]:
dados_2semestre = 'Preços semestrais - AUTOMOTIVOS_2025.02.csv'
df_2semestre = pd.read_csv(dados_2semestre, sep=';')
df_2semestre.head(3)

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,DELMIRO GOUVEIA,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,4431113000100,AVENIDA CAXANGA,126,NaN,PEDRA VELHA,57480-000,DIESEL,01/07/2025,"6,69",NaN,R$ / litro,BRANCA
1,N,AP,MACAPA,SEPE TIARAJU EMPREENDIMENTOS LTDA,5297501000286,RUA SETENTRIONAL,S/N,ESQUINA COM BEIRA RIO,ARAXÁ,68903-640,DIESEL,01/07/2025,"6,33",NaN,R$ / litro,BRANCA
2,NE,BA,IPIRA,AUTO POSTO AUGUSTU'S LTDA,2448248000145,SITIO SAO JOSE,SN,NaN,SEDE,44600-000,DIESEL,01/07/2025,"6,9",NaN,R$ / litro,ALE

In [ ]:
df_2semestre['CNPJ da Revenda'] = df_2semestre['CNPJ da Revenda'].astype

In [ ]:
df_anp = pd.concat([df_1semestre, df_2semestre], ignore_index=True)
df_anp['Valor de Venda'] = df_anp['Valor de Venda'].str.replace(',','.').astype(float) # .astype(float) para mudar de str para float (tipo de dado)
df_anp

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,CE,SOBRAL,ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,GASOLINA,01/01/2025,6.29,NaN,R$ / litro,RAIZEN
1,NE,CE,SOBRAL,ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,GASOLINA ADITIVADA,01/01/2025,6.49,NaN,R$ / litro,RAIZEN
2,NE,CE,SOBRAL,ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,DIESEL S10,01/01/2025,6.19,NaN,R$ / litro,RAIZEN
3,NE,CE,SOBRAL,ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,ETANOL,01/01/2025,5.19,NaN,R$ / litro,RAIZEN
4,NE,CE,SOBRAL,V.C.EMPREENDIMENTOS LTDA,03.551.935/0002-35,AVENIDA JOSE EUCLIDES FERREIRA GOMES,30,POSTO FLASH,CORACAO DE JESUS,62043-070,GASOLINA,01/01/2025,6.53,NaN,R$ / litro,RAIZEN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813726,NE,BA,ALAGOINHAS,2 A COMERCIO DE COMBUSTIVEIS GNV E LUBRIFICANT...,<bound method NDFrame.astype of 0 443...,RODOVIA BR 101 KM 116,S/N,SALA 01,CENTRO,48005-440,GNV,31/12/2025,4.38,NaN,R$ / m3,LARCO
813727,NE,PB,BAYEUX,PETROGAS COMERCIO DE COMBUSTIVEIS LTDA,<bound method NDFrame.astype of 0 443...,AVENIDA LIBERDADE,3545,ANDAR: 1; ANEXO: A;,SESI,58306-000,GNV,31/12/2025,4.85,NaN,R$ / m3,ALE
813728,NE,BA,ILHEUS,BATISTA COMERCIO DE COMBUSTIVEIS E LUBRIFICANT...,<bound method NDFrame.astype of 0 443...,AVENIDA FERROVIARIA,S/N,KM 05 RODOVIA ILHEUS,IGUAPE,45658-340,GNV,31/12/2025,4.73,NaN,R$ / m3,BRANCA
813729,SE,SP,JACAREI,AUTO POSTO BRANCO DE CASTELO LTDA,<bound method NDFrame.astype of 0 443...,AVENIDA SIQUEIRA CAMPOS,641,NaN,CENTRO,12308-190,GNV,31/12/2025,3.99,NaN,R$ / m3,VIBRA
813730,S,RS,LAJEADO,SIM REDE DE POSTOS LTDA,<bound method NDFrame.astype of 0 443...,RODOVIA ERS-130,2285,KM 72.8,SANTO ANDRE,95912-000,GNV,31/12/2025,5.65,NaN,R$ / m3,CHARRUA

In [ ]:
df_gasolina = df_anp.loc[df_anp['Produto'] == 'GASOLINA']
df_etanol = df_anp.loc[df_anp['Produto'] == 'ETANOL']

In [ ]:
df_media_estado_gaso = df_gasolina.groupby('Estado - Sigla')['Valor de Venda'].mean().reset_index()
df_media_estado_gaso = df_media_estado_gaso.sort_values(by='Valor de Venda', ascending= False)

df_media_estado_gaso

   Estado - Sigla  Valor de Venda
0              AC        7.671043
2              AM        7.226496
21             RR        6.947907
20             RO        6.914577
24             SE        6.547728
26             TO        6.534131
6              DF        6.442591
17             PR        6.427747
13             PA        6.401182
23             SC        6.393332
4              BA        6.390745
5              CE        6.373081
1              AL        6.331550
19             RN        6.330973
15             PE        6.330366
8              GO        6.291102
12             MT        6.260951
7              ES        6.256656
22             RS        6.222312
11             MS        6.206580
18             RJ        6.145133
10             MG        6.130570
9              MA        6.128841
25             SP        6.091283
14             PB        6.059165
3              AP        6.041904
16             PI        5.925385

In [ ]:
df_media_estado_etanol = df_etanol.groupby('Estado - Sigla')['Valor de Venda'].mean().reset_index()
df_media_estado_etanol = df_media_estado_etanol.sort_values(by='Valor de Venda', ascending= False)

df_media_estado_etanol

   Estado - Sigla  Valor de Venda
0              AC        5.450321
2              AM        5.429408
3              AP        5.428462
20             RO        5.213401
21             RR        5.164806
5              CE        5.115794
19             RN        4.999004
1              AL        4.974708
9              MA        4.944062
22             RS        4.873926
24             SE        4.853322
13             PA        4.840288
4              BA        4.787785
26             TO        4.773923
15             PE        4.772174
23             SC        4.741009
6              DF        4.641591
16             PI        4.625402
18             RJ        4.610375
7              ES        4.527789
14             PB        4.491290
17             PR        4.457752
8              GO        4.453903
10             MG        4.333693
12             MT        4.160479
25             SP        4.104169
11             MS        4.078334

In [ ]:
df_media_estado_gaso.head(5)

   Estado - Sigla  Valor de Venda
0              AC        7.671043
2              AM        7.226496
21             RR        6.947907
20             RO        6.914577
24             SE        6.547728

In [ ]:
df_media_estado_etanol.head(5)

   Estado - Sigla  Valor de Venda
0              AC        5.450321
2              AM        5.429408
3              AP        5.428462
20             RO        5.213401
21             RR        5.164806

In [ ]:
df_media_regiao_gaso = df_gasolina.groupby('Regiao - Sigla')['Valor de Venda'].mean().reset_index()
df_media_regiao_gaso = df_media_regiao_gaso.sort_values(by='Valor de Venda')
df_media_regiao_gaso

  Regiao - Sigla  Valor de Venda
4             SE        6.115093
2             NE        6.288195
0             CO        6.293839
3              S        6.331845
1              N        6.716720

In [ ]:
df_media_regiao_etanol = df_etanol.groupby('Regiao - Sigla')['Valor de Venda'].mean().reset_index()
df_media_regiao_etanol = df_media_regiao_etanol.sort_values(by='Valor de Venda')
df_media_regiao_etanol

  Regiao - Sigla  Valor de Venda
4             SE        4.237751
0             CO        4.352734
3              S        4.629784
2             NE        4.845289
1              N        5.085354

In [ ]:
df_media_munic = df_gasolina.groupby('Municipio')['Valor de Venda'].mean().reset_index()
df_media_munic

                  Municipio  Valor de Venda
0                ABAETETUBA        6.413960
1                ACAILANDIA        6.461732
2                ADAMANTINA        5.986012
3     AGUAS LINDAS DE GOIAS        6.162500
4                ALAGOINHAS        5.981423
..                      ...             ...
413  VITORIA DE SANTO ANTAO        5.990671
414           VOLTA REDONDA        6.343175
415              VOTORANTIM        6.125492
416             VOTUPORANGA        6.081609
417                 XANXERE        6.354231

[418 rows x 2 columns]

In [ ]:
df_media_munic = df_etanol.groupby('Municipio')['Valor de Venda'].mean().reset_index()
df_media_munic

                  Municipio  Valor de Venda
0                ABAETETUBA        5.007857
1                ACAILANDIA        4.893571
2                ADAMANTINA        3.958328
3     AGUAS LINDAS DE GOIAS        4.381119
4                ALAGOINHAS        4.514440
..                      ...             ...
410  VITORIA DE SANTO ANTAO        4.494523
411           VOLTA REDONDA        4.838187
412              VOTORANTIM        4.161813
413             VOTUPORANGA        3.889227
414                 XANXERE        4.809091

[415 rows x 2 columns]

In [ ]:
df_media_munic_gaso = df_gasolina.groupby('Municipio')['Valor de Venda'].mean().reset_index()
df_media_munic_gaso.head(10)
df_media_munic_gaso.head(-10)

                 Municipio  Valor de Venda
0               ABAETETUBA        6.413960
1               ACAILANDIA        6.461732
2               ADAMANTINA        5.986012
3    AGUAS LINDAS DE GOIAS        6.162500
4               ALAGOINHAS        5.981423
..                     ...             ...
403          VARZEA GRANDE        6.149532
404        VARZEA PAULISTA        5.978778
405                 VIAMAO        6.067991
406                 VICOSA        6.278969
407                VIDEIRA        6.333941

[408 rows x 2 columns]

In [ ]:
df_media_munic_etanol = df_etanol.groupby('Municipio')['Valor de Venda'].mean().reset_index()
df_media_munic_etanol.head(10)
df_media_munic_etanol.head(-10)

                 Municipio  Valor de Venda
0               ABAETETUBA        5.007857
1               ACAILANDIA        4.893571
2               ADAMANTINA        3.958328
3    AGUAS LINDAS DE GOIAS        4.381119
4               ALAGOINHAS        4.514440
..                     ...             ...
400          VARZEA GRANDE        4.097623
401        VARZEA PAULISTA        4.085639
402                 VIAMAO        4.874105
403                 VICOSA        4.548984
404                VIDEIRA        4.958163

[405 rows x 2 columns]

In [ ]:
df_combustiveis_RJ = df_anp.loc[df_anp['Estado - Sigla'] == 'RJ']
df_combustiveis_RJ

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
54,SE,RJ,CAMPOS DOS GOYTACAZES,POSTO DE COMBUSTIVEIS CONTORNO DE CAMPOS LTDA,31.212.889/0002-85,AVENIDA NILO PECANHA,614,/822 PATIO,PQ SANTO AMARO,28030-035,GNV,01/01/2025,5.39,NaN,R$ / m³,VIBRA
55,SE,RJ,CAMPOS DOS GOYTACAZES,POSTO DE COMBUSTIVEIS CONTORNO DE CAMPOS LTDA,31.212.889/0002-85,AVENIDA NILO PECANHA,614,/822 PATIO,PQ SANTO AMARO,28030-035,GASOLINA,01/01/2025,6.49,NaN,R$ / litro,VIBRA
56,SE,RJ,CAMPOS DOS GOYTACAZES,POSTO DE COMBUSTIVEIS CONTORNO DE CAMPOS LTDA,31.212.889/0002-85,AVENIDA NILO PECANHA,614,/822 PATIO,PQ SANTO AMARO,28030-035,GASOLINA ADITIVADA,01/01/2025,6.69,NaN,R$ / litro,VIBRA
57,SE,RJ,CAMPOS DOS GOYTACAZES,POSTO DE COMBUSTIVEIS CONTORNO DE CAMPOS LTDA,31.212.889/0002-85,AVENIDA NILO PECANHA,614,/822 PATIO,PQ SANTO AMARO,28030-035,ETANOL,01/01/2025,4.79,NaN,R$ / litro,VIBRA
58,SE,RJ,CAMPOS DOS GOYTACAZES,POSTO DE COMBUSTIVEIS B J LTDA,06.211.735/0001-40,RUA BENEDITO QUEIROZ,1,NaN,TURF CLUB,28024-040,GASOLINA,01/01/2025,6.42,NaN,R$ / litro,BRANCA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813694,SE,RJ,SAQUAREMA,CENTRO AUTOMOTIVO SAQUAREMA GAS LTDA,<bound method NDFrame.astype of 0 443...,RUA ADILSON OLIVEIRA,SN,LOTE 29,SAO GERALDO ( BACAXA),28995-175,GNV,30/12/2025,5.99,NaN,R$ / m3,BRANCA
813698,SE,RJ,TRES RIOS,POSTO DE ABASTECIMENTO TRERIENSE LTDA,<bound method NDFrame.astype of 0 443...,RUA NELSON VIANA,552,NaN,PORTAO VERMELHO,25805-290,GNV,30/12/2025,5.89,NaN,R$ / m3,BRANCA
813699,SE,RJ,BELFORD ROXO,AUTO POSTO CASCAO LTDA,<bound method NDFrame.astype of 0 443...,AVENIDA JOAQUIM DA COSTA LIMA,3351,NaN,NOVA PIAM,26115-085,GNV,30/12/2025,4.59,NaN,R$ / m3,BRANCA
813713,SE,RJ,TRES RIOS,AUTO LUBRIFICADORA TRIRRIENSE LTDA,<bound method NDFrame.astype of 0 443...,RUA BARAO DE ENTRE RIOS,401,NaN,CENTRO,25802-315,GNV,31/12/2025,5.99,NaN,R$ / m3,IPIRANGA
813725,SE,RJ,ANGRA DOS REIS,VALE DO CAFE AUTO POSTO LTDA,<bound method NDFrame.astype of 0 443...,RUA ITATIAIA,S/N,NaN,JAPUIBA,23900-010,GNV,31/12/2025,5.98,NaN,R$ / m3,BRANCA

In [ ]:
df_media_todos_combus_RJ = df_combustiveis_RJ.groupby('Produto')['Valor de Venda'].mean().reset_index()
df_media_todos_combus_RJ

              Produto  Valor de Venda
0              DIESEL        6.175443
1          DIESEL S10        6.239853
2              ETANOL        4.610375
3            GASOLINA        6.145133
4  GASOLINA ADITIVADA        6.337924
5                 GNV        4.712781

In [ ]:
df_todos_combus_RJ_munic = df_combustiveis_RJ.groupby(['Municipio', 'Produto'])['Valor de Venda'].mean().reset_index()
df_todos_combus_RJ_munic = df_todos_combus_RJ_munic.sort_values(by= 'Valor de Venda')
df_todos_combus_RJ_munic

          Municipio             Produto  Valor de Venda
83          NITEROI                 GNV        4.230796
130     SAO GONCALO                 GNV        4.265483
80          NITEROI              ETANOL        4.357583
74        NILOPOLIS              ETANOL        4.409333
118  RIO DE JANEIRO                 GNV        4.414796
..              ...                 ...             ...
4    ANGRA DOS REIS  GASOLINA ADITIVADA        6.821928
0    ANGRA DOS REIS              DIESEL        6.848582
60            MACAE              DIESEL        6.854136
61            MACAE          DIESEL S10        6.905903
1    ANGRA DOS REIS          DIESEL S10        6.967542

[161 rows x 3 columns]